version: '3'
services:
  nginx:
    image: nginx:latest
    container_name: my-nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro


  backend:
    build:
      context: ./test_public_api
    container_name: backend
    restart: always
    ports:
      - "3000:3000"
